
registry: ""
hostname: ""
images:
  #frontend:
  #  dockerfile: KargoDemo/Dockerfile
  #  context: .
  #  port: 80
  #  ingressRoute: /
  #  image: ghcr.io/paritytech-stg/kargodemo:latest
  #backend:
  #  dockerfile: KargoDemoServer/Dockerfile
  #  context: .
  #  port: 5000
  #  ingressRoute: /api
  #  image: ghcr.io/paritytech-stg/kargodemoserver:latest
